---
- name: pkg deps
  become: yes
  become_user: root
  command: apk add --no-cache --virtual=.build-dependencies wget ca-certificates

- name: downloading {{ alpine_glibc_shim_key_url }} to {{ alpine_glibc_shim_key_path }}
  become: yes
  become_user: root
  get_url:
    url: '{{ alpine_glibc_shim_key_url }}'
    dest: '{{ alpine_glibc_shim_key_path }}'

- name: downloading v{{ alpine_glibc_shim_ver }} pkgs from {{ alpine_glibc_shim_mirror }}...
  become: yes
  become_user: root
  with_items: '{{ alpine_glibc_shim_pkg_prefixes }}'
  get_url:
    url: '{{ alpine_glibc_shim_mirror_ver }}/{{ item }}-{{ alpine_glibc_shim_ver }}.apk'
    dest: /tmp/{{ item }}-{{ alpine_glibc_shim_ver }}.apk
    checksum: '{{ alpine_glibc_shim_checksums[alpine_glibc_shim_ver][item] }}'
    mode: 0644

- name: installing v{{ alpine_glibc_shim_ver }} pkgs...
  become: yes
  become_user: root
  with_items: '{{ alpine_glibc_shim_pkg_prefixes }}'
  command: apk add --no-cache /tmp/{{ item }}-{{ alpine_glibc_shim_ver }}.apk

- name: fix locales...
  become: yes
  become_user: root
  command: /usr/glibc-compat/bin/localedef --force --inputfile POSIX --charmap UTF-8 C.UTF-8
  ignore_errors: True

- name: template default local for sh
  become: yes
  become_user: root
  with_items:
    - f: locale.sh
      d: /etc/profile.d
      m: '0644'
  template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m }}'

- name: cleanup...
  become: yes
  become_user: root
  with_items:
    - glibc-i18n
    - .build-dependencies
  command: apk del {{ item }}
